import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useState } from "react";


export default function Home() {
  const [data, setData] = useState({});
  const [location, setLocation] = useState('');
  const [weather, setWeather] = useState();
  const [errorMessage, setErrorMessage] = useState('');

  var apiKey = "719f7a49bd9411a06ffbf260dc0f41a9";
  var lang = "en";
  var units = "metric";
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`;

  const searchLocation = (event) => {
    if(event.key === "Enter"){
      axios.get(url)
        .then((response) => {
          console.clear();
          setData(response.data)
          console.log(response.data)
          setWeather(response.data.weather)
          setErrorMessage("")
        }).catch(err => {
          console.log(err)
          setErrorMessage("Please enter another location")
          setData({})
          setWeather()
        })
        setLocation('');
    }
  }

  return (
    <div>
      <Head>
        <title>Weather</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      {errorMessage}
      <div className="header">What's the Weather? ☀️ 🌧️ ❄️</div>
        <input className="enter"
          value={location}
          onChange={(event) => setLocation(event.target.value)}
          placeholder="Enter location"
          onKeyDown={searchLocation}
          type="text"
        />
        <div className="city">
          {data.name}
        </div>
        {
          weather && weather.map((w, index) => {
            return(
              <div key={index} className="cont">
                <div className="temp">Temperature is <span className="num">{data.main.temp}°C</span> 🌡️</div>
                <div className="feels">Feels like <span className="num">{data.main.feels_like}°C</span> 🤔</div>
                <div className="wind">Wind <span className="num">{data.wind.speed}m/s</span> 💨</div>
              </div>
            )
          })
        }
      </main>
    </div>
  );
}
